import { useEffect, useMemo, useState } from 'react';
import { TRANSITION_ACTIONS, dateTime, orderCode, orderDestination, orderOrigin, statusClass } from './ui20-model.js';

export const Metric = ({ label, value, detail }) => <article className="metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;
export const Stream = ({ value }) => <span className={`stream-status stream-${String(value).toLowerCase()}`}><i />{value}</span>;

export function EquipmentPanel({ jobLists, telemetry, onDetails }) {
  const live = useMemo(() => new Map(telemetry.map((item) => [item.equipamento, item])), [telemetry]);
  return <section className="panel"><div className="section-head"><div><span className="eyebrow">Equipment Control</span><h2>Job lists por equipamento</h2></div><span>{jobLists.length}</span></div>{!jobLists.length ? <p className="empty">Nenhum CHE com filas nesta visita.</p> : <div className="equipment-grid">{jobLists.map((equipment) => {
    const jobs = (equipment.workQueues || []).flatMap((queue) => queue.jobList || []); const telemetryItem = live.get(equipment.equipamentoIdentificador);
    return <article className="equipment-card" key={equipment.equipamentoPatioId}><div className="equipment-head"><div><strong>{equipment.equipamentoIdentificador}</strong><small>{equipment.equipamentoTipo} · ID {equipment.equipamentoPatioId}</small></div><span className={statusClass(equipment.equipamentoStatus)}>{equipment.equipamentoStatus}</span></div><div className="equipment-metrics"><span><b>{equipment.totalInstrucoes}</b> jobs</span><span><b>{jobs.filter((job) => job.statusOrdem === 'EM_EXECUCAO').length}</b> executando</span><span><b>{equipment.totalFilas}</b> filas</span></div><small>{telemetryItem ? `${telemetryItem.posicaoMaisProxima || 'sem posição'} · VMT ${telemetryItem.statusVmt || '—'} · ${dateTime(telemetryItem.recebidoEm)}` : 'Sem telemetria recente.'}</small><div className="equipment-jobs">{jobs.slice(0, 8).map((job) => <button className="job-chip" key={job.id} onClick={() => onDetails(job)}>{orderCode(job)}<small>{job.statusOrdem} · seq. {job.sequenciaNavio || '—'}</small></button>)}</div></article>;
  })}</div>}</section>;
}

export function WorkQueues({ queues, plan, jobLists, matrix, edits, expanded, busyKey, onEdit, onSave, onToggle, onDetails, onTransition }) {
  return <section className="panel"><div className="section-head"><div><span className="eyebrow">Yard</span><h2>Work queues e work instructions</h2></div><span>{queues.length}</span></div>{queues.map((queue) => {
    const key = queue.id || queue.identificador; const jobs = queue.jobList || []; const edit = edits[queue.id] || {};
    return <article className={`queue ${queue.id ? '' : 'queue-derived'}`} key={key}><button className="queue-head" onClick={() => onToggle(key)}><span><strong>{queue.identificador}</strong><small>{queue.berco || 'sem berço'} · {queue.blocoZona || 'sem zona'}</small></span><span><span className={statusClass(queue.status)}>{queue.status}</span><strong>{jobs.length || queue.totalOrdens || 0} jobs</strong>{expanded[key] ? '▴' : '▾'}</span></button>{expanded[key] && <div className="queue-body">
      {queue.id ? <div className="resource-editor"><label>Porão<input type="number" min="1" value={edit.porao ?? ''} onChange={(event) => onEdit(queue.id, { ...edit, porao: event.target.value })} /></label><label>Plano<select value={edit.planoGuindasteId ?? ''} onChange={(event) => onEdit(queue.id, { ...edit, planoGuindasteId: event.target.value })}><option value="">Sem vínculo</option>{(plan?.guindastes || []).map((item) => <option key={item.id} value={item.id}>{item.codigoGuindaste} · porão {item.porao}</option>)}</select></label><label>Recurso de cais (ID)<input type="number" min="1" value={edit.recursoCaisId ?? ''} onChange={(event) => onEdit(queue.id, { ...edit, recursoCaisId: event.target.value })} /></label><label>CHE real<select value={edit.equipamentoPatioId ?? ''} onChange={(event) => onEdit(queue.id, { ...edit, equipamentoPatioId: event.target.value })}><option value="">Sem CHE</option>{jobLists.map((item) => <option key={item.equipamentoPatioId} value={item.equipamentoPatioId}>{item.equipamentoIdentificador} · {item.equipamentoTipo}</option>)}</select></label><button disabled={busyKey === `resources-${queue.id}`} onClick={() => onSave(queue)}>Salvar recursos</button></div> : <div className="message error">Fila derivada: corrija a cobertura no Yard.</div>}
      <div className="coverage-summary"><span>POW<b>{queue.pow || 'não associado'}</b></span><span>Pool<b>{queue.poolOperacional || 'não associado'}</b></span><span>CHE<b>{queue.equipamento || 'não associado'}</b></span><span>Plano<b>{queue.planoGuindasteId || 'não associado'}</b></span></div>
      {!jobs.length ? <p className="empty">Sem work instructions.</p> : <div className="table-wrap nested"><table><thead><tr><th>Unidade</th><th>Status</th><th>Origem</th><th>Destino</th><th>Seq.</th><th>Ações oficiais</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td><strong>{orderCode(job)}</strong></td><td><span className={statusClass(job.statusOrdem)}>{job.statusOrdem}</span></td><td>{orderOrigin(job)}</td><td>{orderDestination(job)}</td><td>{job.sequenciaNavio || '—'}</td><td><div className="actions"><button className="small secondary" onClick={() => onDetails(job)}>Drill-down</button>{(matrix[job.statusOrdem] || []).filter((target) => TRANSITION_ACTIONS[target]).map((target) => <button className="small warning" key={target} disabled={busyKey === `transition-${job.id}`} onClick={() => onTransition(job, target)}>{TRANSITION_ACTIONS[target][0]}</button>)}</div></td></tr>)}</tbody></table></div>}
    </div>}</article>;
  })}</section>;
}

export function DrillDown({ detail, busy, onClose, onTransition, onPriority }) {
  const instruction = detail?.workInstruction; const [priority, setPriority] = useState(0); const [fetchPriority, setFetchPriority] = useState(false);
  useEffect(() => { setPriority(instruction?.prioridadeOperacional || 0); setFetchPriority(Boolean(instruction?.prioridadeBusca)); }, [instruction?.id, instruction?.prioridadeOperacional, instruction?.prioridadeBusca]);
  if (!instruction) return null;
  return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside className="instruction-drawer"><div className="drawer-head"><div><span className="eyebrow">Work instruction oficial</span><h2>{orderCode(instruction)}</h2></div><button className="secondary" onClick={onClose}>Fechar</button></div><div className="detail-grid"><article><span>Status</span><strong className={statusClass(instruction.statusOrdem)}>{instruction.statusOrdem}</strong></article><article><span>Work queue</span><strong>{detail.workQueue?.identificador || 'Sem fila'}</strong></article><article><span>POW / Pool</span><strong>{detail.workQueue?.pow || 'sem POW'} · {detail.workQueue?.poolOperacional || 'sem pool'}</strong></article><article><span>CHE real</span><strong>{detail.equipamentoIdentificador || 'sem CHE'} {detail.equipamentoPatioId ? `(ID ${detail.equipamentoPatioId})` : ''}</strong></article><article><span>Origem</span><strong>{orderOrigin(instruction)}</strong></article><article><span>Destino</span><strong>{orderDestination(instruction)}</strong></article></div>
    <section className="drawer-section"><h3>Prioridades</h3><div className="priority-editor"><label>Operacional<input type="number" min="0" value={priority} onChange={(event) => setPriority(Number(event.target.value))} /></label><label className="check-label"><input type="checkbox" checked={fetchPriority} onChange={(event) => setFetchPriority(event.target.checked)} /> Prioridade de fetch</label><button disabled={busy} onClick={() => onPriority(instruction, priority, fetchPriority)}>Salvar</button></div></section>
    <section className="drawer-section"><h3>Transições permitidas</h3><div className="actions">{(detail.proximosEstadosPermitidos || []).filter((target) => TRANSITION_ACTIONS[target]).map((target) => <button className="warning" disabled={busy} key={target} onClick={() => onTransition(instruction, target)}>{TRANSITION_ACTIONS[target][0]}</button>)}</div></section>
    <section className="drawer-section"><h3>Matriz oficial</h3><pre>{JSON.stringify(detail.matrizOficialEstados, null, 2)}</pre></section><section className="drawer-section"><h3>Auditoria</h3><div className="timeline">{(detail.auditoria || []).map((entry, index) => <article key={entry.id || index}><time>{dateTime(entry.criadoEm)}</time><div><strong>{entry.acao}</strong><p>{entry.motivo || 'Sem motivo.'}</p><small>{entry.usuario} · {entry.detalhes}</small></div></article>)}</div></section>
  </aside></div>;
}
