image: marcopeg/gitpod-workspace-postgres:2.5.0

ports:
  - port: 8008
    onOpen: open-preview
  - port: 5432
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 4200
    onOpen: open-preview

tasks:
  - init: |
      cd frontend/cloudport
       rm -rf node_modules package-lock.json
      nvm install node
      nvm use node
      npm install -g @angular/cli
      npm install -g npm 
      npm install @angular/core
      npm install --save ag-grid-community
      npm install --save ag-grid-angular
      npm install --save ngx-mask
      npm i ngx-mask@13.1.13
      npm install xlsx
      npm install --save-dev @angular-devkit/build-angular
      npm install @angular/material
      npm install --save @ag-grid-community/core


     
      npm install



      


    command: ng serve

