image: gitpod/workspace-postgres

ports:
  - port: 8008
    onOpen: open-preview
  - port: 5432
    onOpen: open-preview

tasks:
  - init: |
      cd frontend/cloudport
      nvm install node
      nvm use node

      npm install -g npm 
      npm uninstall -g @angular/cli
      npm uninstall -g @angular/common
      npm uninstall -g @angular/core
      npm uninstall -g @angular/animations
      npm cache verify
      rm -rf node_modules package-lock.json


      npm install -g @angular/cli
      npm install --save @angular/core@15.0.0 --legacy-peer-deps
      npm install --save @angular/common@15.0.0 --legacy-peer-deps
      npm install --save @angular/forms@15.0.0 --legacy-peer-deps
      npm install --save @angular/animations@15.0.0 --legacy-peer-deps
      npm install --save @angular/cdk@15.0.0 --legacy-peer-deps
      npm install --save angular-bootstrap-md --legacy-peer-deps
      npm install --save ngx-mask --legacy-peer-deps
      npm install --legacy-peer-deps
    command: ng serve
