image:
  file: docker/Dockerfile

ports:
  - port: 8008
    onOpen: open-preview
  - port: 5432
    onOpen: open-preview

tasks:
  - init: |
      sudo -u postgres createdb servico_autenticacao
      cd frontend/cloudport
      nvm install node
      nvm use node
      npm install -g @angular/cli
      npm install -g npm 
      npm install
      npm install --save ngx-mask
      npm i ngx-mask@13.1.13
    command: ng serve
