image: marcopeg/gitpod-workspace-postgres:2.5.0

ports:
  - port: 8008
    onOpen: open-browser
  - port: 5432
    onOpen: open-browser

tasks:
  - init: |
      cd frontend/cloudport
      nvm install node
      nvm use node
      npm install -g @angular/cli
      npm install -g npm 
      npm install
      npm install --save ngx-mask
      npm i ngx-mask@13.1.13
    command: ng serve
