-- BUS20: dados hidrostaticos e estruturais versionados e memoria de aprovacao

ALTER TABLE estivagem_plan
    ALTER COLUMN comprimento_lpp DROP DEFAULT,
    ALTER COLUMN boca DROP DEFAULT,
    ALTER COLUMN calado DROP DEFAULT,
    ALTER COLUMN deslocamento DROP DEFAULT,
    ALTER COLUMN gm DROP DEFAULT,
    ALTER COLUMN tpc DROP DEFAULT,
    ALTER COLUMN lcb DROP DEFAULT;

ALTER TABLE estivagem_plan
    ADD COLUMN IF NOT EXISTS km DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS mct_1cm DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS calado_maximo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS trim_maximo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS banda_maxima DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS gm_minimo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS peso_leve_t DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS tcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS vcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS peso_lastro_t DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS tcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS vcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS versao_dados_hidrostaticos VARCHAR(80),
    ADD COLUMN IF NOT EXISTS versao_dados_estruturais VARCHAR(80),
    ADD COLUMN IF NOT EXISTS posicoes_secoes TEXT,
    ADD COLUMN IF NOT EXISTS peso_leve_secoes TEXT,
    ADD COLUMN IF NOT EXISTS empuxo_secoes TEXT,
    ADD COLUMN IF NOT EXISTS limites_sf_secoes TEXT,
    ADD COLUMN IF NOT EXISTS limites_bm_secoes TEXT,
    ADD COLUMN IF NOT EXISTS calado_calculado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS gm_calculado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS sf_max_calculado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS bm_max_calculado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS versao_hidro_aprovacao VARCHAR(80),
    ADD COLUMN IF NOT EXISTS versao_estrutural_aprovacao VARCHAR(80),
    ADD COLUMN IF NOT EXISTS memoria_calculo_aprovacao TEXT,
    ADD COLUMN IF NOT EXISTS aprovado_em TIMESTAMP;

ALTER TABLE slot_navio
    ADD COLUMN IF NOT EXISTS pos_longitudinal_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS pos_transversal_m DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS pos_vertical_m DOUBLE PRECISION;

ALTER TABLE navio_granel
    ALTER COLUMN gm DROP DEFAULT;

ALTER TABLE navio_granel
    ADD COLUMN IF NOT EXISTS tpc DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lcb DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS km DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS mct_1cm DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS calado_maximo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS trim_maximo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS banda_maxima DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS gm_minimo DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS peso_leve_t DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS tcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS vcg_peso_leve DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS peso_lastro_t DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS lcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS tcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS vcg_lastro DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS versao_dados_hidrostaticos VARCHAR(80),
    ADD COLUMN IF NOT EXISTS versao_dados_estruturais VARCHAR(80),
    ADD COLUMN IF NOT EXISTS posicoes_secoes TEXT,
    ADD COLUMN IF NOT EXISTS peso_leve_secoes TEXT,
    ADD COLUMN IF NOT EXISTS empuxo_secoes TEXT,
    ADD COLUMN IF NOT EXISTS limites_sf_secoes TEXT,
    ADD COLUMN IF NOT EXISTS limites_bm_secoes TEXT;

ALTER TABLE plano_estiva_bulk
    ADD COLUMN IF NOT EXISTS gm_calculado DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS versao_hidro_aprovacao VARCHAR(80),
    ADD COLUMN IF NOT EXISTS versao_estrutural_aprovacao VARCHAR(80),
    ADD COLUMN IF NOT EXISTS memoria_calculo_aprovacao TEXT,
    ADD COLUMN IF NOT EXISTS aprovado_em TIMESTAMP;
