version: '3.9'

services:
  servico-gate:
    build:
      context: ..
      dockerfile: backend/servico-gate/Dockerfile
    image: ${CI_DOCKER_IMAGE:-cloudport/servico-gate:local}
    ports:
      - "${GATE_SERVER_PORT:-8082}:8082"
    env_file:
      - ../.env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      GATE_DB_URL: jdbc:postgresql://servico-gate-db:5432/servico_gate
      GATE_DB_USERNAME: ${GATE_DB_USERNAME:-postgres}
      GATE_DB_PASSWORD: ${GATE_DB_PASSWORD:-postgres}
      GATE_RABBIT_HOST: servico-gate-rabbitmq
      GATE_RABBIT_PORT: 5672
      GATE_RABBIT_USERNAME: ${GATE_RABBIT_USERNAME:-guest}
      GATE_RABBIT_PASSWORD: ${GATE_RABBIT_PASSWORD:-guest}
      GATE_CACHE_HOST: servico-gate-redis
      DOCUMENT_STORAGE_PROVIDER: local
      DOCUMENT_STORAGE_BASE_PATH: /data/documents
      DOCUMENT_STORAGE_BUCKET: cloudport-documents
      TOS_API_BASE_URL: http://mock-tos:8080
      AUTH_API_BASE_URL: http://mock-auth:8080
    depends_on:
      - servico-gate-db
      - servico-gate-rabbitmq
      - servico-gate-redis

  servico-gate-db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: servico_gate
      POSTGRES_USER: ${GATE_DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${GATE_DB_PASSWORD:-postgres}
    volumes:
      - servico-gate-db-data:/var/lib/postgresql/data

  servico-gate-rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${GATE_RABBIT_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${GATE_RABBIT_PASSWORD:-guest}
    volumes:
      - servico-gate-rabbitmq-data:/var/lib/rabbitmq

  servico-gate-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - servico-gate-redis-data:/data

  mock-tos:
    image: ghcr.io/cloudport/mock-tos:latest
    ports:
      - "8084:8080"

  mock-auth:
    image: ghcr.io/cloudport/mock-auth:latest
    ports:
      - "8085:8080"

volumes:
  servico-gate-db-data:
  servico-gate-rabbitmq-data:
  servico-gate-redis-data:
