package br.com.cloudport.servicoautenticacao.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

class UserInitializerTest {

    private static final String EMAIL_ROOT = "root@cloudport.local";
    private static final String SENHA_ROOT = "SenhaRoot123!";

    private JdbcTemplate jdbcTemplate;
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    void configurarBanco() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:user-initializer;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        dataSource.setUsername("sa");
        dataSource.setPassword("");

        jdbcTemplate = new JdbcTemplate(dataSource);
        passwordEncoder = new BCryptPasswordEncoder();

        jdbcTemplate.execute("DROP TABLE IF EXISTS user_roles");
        jdbcTemplate.execute("DROP TABLE IF EXISTS roles");
        jdbcTemplate.execute("DROP TABLE IF EXISTS users");
        jdbcTemplate.execute("CREATE TABLE users (" +
                "id UUID PRIMARY KEY, " +
                "login VARCHAR(255) NOT NULL UNIQUE, " +
                "password VARCHAR(255), " +
                "nome VARCHAR(255), " +
                "transportadora_documento VARCHAR(255), " +
                "transportadora_nome VARCHAR(255))");
        jdbcTemplate.execute("CREATE TABLE roles (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(255) NOT NULL UNIQUE)");
        jdbcTemplate.execute("CREATE TABLE user_roles (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id UUID NOT NULL, " +
                "role_id BIGINT NOT NULL, " +
                "status VARCHAR(20) NOT NULL)");
    }

    @Test
    void deveCriarRootAtualizarSenhaEConcederTodosOsPapeis() throws Exception {
        jdbcTemplate.update("INSERT INTO roles (name) VALUES (?)", "ROLE_AUDITOR");
        jdbcTemplate.update(
                "INSERT INTO users (id, login, password, nome) VALUES (?, ?, ?, ?)",
                UUID.randomUUID(),
                EMAIL_ROOT,
                passwordEncoder.encode("SenhaAnterior123!"),
                "Usuário anterior");

        UserInitializer initializer = new UserInitializer(
                jdbcTemplate,
                passwordEncoder,
                EMAIL_ROOT,
                SENHA_ROOT);

        initializer.run();

        String senhaPersistida = jdbcTemplate.queryForObject(
                "SELECT password FROM users WHERE login = ?",
                String.class,
                EMAIL_ROOT);
        String nomePersistido = jdbcTemplate.queryForObject(
                "SELECT nome FROM users WHERE login = ?",
                String.class,
                EMAIL_ROOT);
        List<String> papeis = jdbcTemplate.queryForList(
                "SELECT r.name " +
                        "FROM roles r " +
                        "JOIN user_roles ur ON ur.role_id = r.id " +
                        "JOIN users u ON u.id = ur.user_id " +
                        "WHERE u.login = ? AND ur.status = 'ATIVO'",
                String.class,
                EMAIL_ROOT);

        assertTrue(passwordEncoder.matches(SENHA_ROOT, senhaPersistida));
        assertEquals("Root do sistema", nomePersistido);
        assertTrue(papeis.contains("ROLE_ROOT"));
        assertTrue(papeis.contains("ROLE_ADMIN_PORTO"));
        assertTrue(papeis.contains("ROLE_AUDITOR"));
        assertEquals(
                jdbcTemplate.queryForObject("SELECT COUNT(*) FROM roles", Integer.class),
                papeis.size());
    }
}
