CREATE TABLE IF NOT EXISTS ordem_movimentacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_trem_id BIGINT NOT NULL,
    codigo_conteiner VARCHAR(20) NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    status_movimentacao VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_ordem_movimentacao_visita
        FOREIGN KEY (visita_trem_id) REFERENCES visita_trem (id) ON DELETE CASCADE,
    CONSTRAINT uk_ordem_visita_conteiner_tipo
        UNIQUE (visita_trem_id, codigo_conteiner, tipo_movimentacao)
);
