ALTER TABLE visita_trem
    ADD COLUMN versao BIGINT NOT NULL DEFAULT 0;

ALTER TABLE visita_trem_vagao
    ADD COLUMN capacidade_conteineres INTEGER NOT NULL DEFAULT 2;

ALTER TABLE ordem_movimentacao
    ADD COLUMN identificador_vagao VARCHAR(35);

ALTER TABLE ordem_movimentacao
    ADD COLUMN posicao_vagao_no_trem INTEGER;

CREATE TABLE replanejamento_conteiner_ferroviario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_trem_id BIGINT NOT NULL,
    codigo_conteiner VARCHAR(20) NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    vagao_origem VARCHAR(35) NOT NULL,
    posicao_origem INTEGER NOT NULL,
    vagao_destino VARCHAR(35) NOT NULL,
    posicao_destino INTEGER NOT NULL,
    ordem_manifesto_origem INTEGER NOT NULL,
    ordem_manifesto_destino INTEGER NOT NULL,
    usuario_operacao VARCHAR(120) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    versao_anterior BIGINT NOT NULL,
    versao_atual BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_replanejamento_visita
        FOREIGN KEY (visita_trem_id) REFERENCES visita_trem (id) ON DELETE CASCADE
);

CREATE INDEX idx_replanejamento_visita_data
    ON replanejamento_conteiner_ferroviario (visita_trem_id, criado_em);

CREATE INDEX idx_replanejamento_conteiner
    ON replanejamento_conteiner_ferroviario (codigo_conteiner);
