ALTER TABLE visita_trem
    ADD COLUMN IF NOT EXISTS versao BIGINT NOT NULL DEFAULT 0;

ALTER TABLE visita_trem_vagao
    ADD COLUMN IF NOT EXISTS capacidade_conteineres INTEGER NOT NULL DEFAULT 2;

CREATE TABLE IF NOT EXISTS ordem_movimentacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_trem_id BIGINT NOT NULL,
    codigo_conteiner VARCHAR(20) NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    status_movimentacao VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_ordem_movimentacao_visita
        FOREIGN KEY (visita_trem_id) REFERENCES visita_trem (id) ON DELETE CASCADE,
    CONSTRAINT uk_ordem_visita_conteiner_tipo
        UNIQUE (visita_trem_id, codigo_conteiner, tipo_movimentacao)
);

ALTER TABLE ordem_movimentacao
    ADD COLUMN IF NOT EXISTS identificador_vagao VARCHAR(35);

ALTER TABLE ordem_movimentacao
    ADD COLUMN IF NOT EXISTS posicao_vagao_no_trem INTEGER;

CREATE TABLE IF NOT EXISTS replanejamento_conteiner_ferroviario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_trem_id BIGINT NOT NULL,
    codigo_conteiner VARCHAR(20) NOT NULL,
    tipo_movimentacao VARCHAR(20) NOT NULL,
    vagao_origem VARCHAR(35) NOT NULL,
    posicao_origem INTEGER NOT NULL,
    vagao_destino VARCHAR(35) NOT NULL,
    posicao_destino INTEGER NOT NULL,
    ordem_manifesto_origem INTEGER NOT NULL,
    ordem_manifesto_destino INTEGER NOT NULL,
    usuario_operacao VARCHAR(120) NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    versao_anterior BIGINT NOT NULL,
    versao_atual BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_replanejamento_visita
        FOREIGN KEY (visita_trem_id) REFERENCES visita_trem (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_replanejamento_visita_data
    ON replanejamento_conteiner_ferroviario (visita_trem_id, criado_em);

CREATE INDEX IF NOT EXISTS idx_replanejamento_conteiner
    ON replanejamento_conteiner_ferroviario (codigo_conteiner);
